# General chron configuration
chron:
  node: chron
  ingest:
    endpoint: http://localhost:8081/
    username: ingest-admin
    password: replace-me
  replicatingTo:
    - ucsd
    - umiacs
  stage.bags:
    posix.path: /export/bags
    posix.id: 1

ace.ims:
  port: 8080
  endpoint: ims.umiacs.umd.edu
  waitTime: 5000

dpn:
  endpoint: http://localhost:3000/
  username: chron
  api-key: replace-me

duracloud:
  snapshots: /export/snapshots/
  restores: /export/restore/
  bridge: 
    username: bridge
    password: replace-me
    endpoint: http://localhost:8080/

spring.pid.file: /var/run/bridge-intake.pid

disableSNI: false
dpnReplicationServer: dpn-staging.ucsd.edu
pushDPN: false
pushChronopolis: false

bridge:
  poll: 0 0 0 * * *

logging:
  file: /var/log/chronopolis/bridge-intake.log
  level:
    org.chronopolis: debug
    org.chronopolis.intake.duracloud.config: trace
