# General chron configuration
chron:
  node: chron
  stage.bags:
    posix.path: /export/bags
    posix.id: 1

ingest.api:
  endpoint: http://localhost:8000/
  username: replace-me
  password: replace-me

ace.ims:
  port: 8080
  endpoint: ims.umiacs.umd.edu
  waitTime: 5000

dpn:
  endpoint: http://localhost:3000/
  username: chron
  api-key: replace-me

duracloud:
  bridge:
    - name: bridge-0
      snapshots: /bridge-0/snapshots/
      restores: /bridge-0/restore/
      username: replace-me
      password: replace-me
      endpoint: http://localhost:8080/
      push: DPN
    - name: bridge-1
      snapshots: /bridge-1/snapshots/
      restores: /bridge-1/restore/
      username: replace-me
      password: replace-me
      endpoint: http://localhost:8081/

spring.pid.file: /var/run/bridge-intake.pid

disableSNI: false
dpnReplicationServer: dpn-staging.ucsd.edu

bridge:
  poll: 0 0 0 * * *

logging:
  file: bridge-intake.log
  level:
    org.chronopolis: debug
    org.chronopolis.intake.duracloud.config: trace
